export { Register } from "./Register/Register";
export { TnC } from "./TnC/TnC";
export { PrivacyPolicy } from "./PrivacyPolicy/PrivacyPolicy";
export { LogIn } from "./Login/LogIn";
export { LogOut } from "./LogOut";
export { Home } from "./Home/Home";
export { MyToolBanks } from "./MyToolBanks/MyToolBanks";
export { PostTool } from "./PostTool/PostTool";
export { PrivateRoute } from "./PrivateRoute";
