export { Home } from "./Home/Home";
export { Register } from "./Register/Register";
export { LogIn } from "./Login/LogIn";
export { LogOut } from "./LogOut";
export { Navigation } from "./Navigation/Navigation";
export { Footer } from "./Footer/Footer";
export { PrivateRoute } from "./PrivateRoute";
export { TnC } from "./TnC/TnC";
export { PrivacyPolicy } from "./PrivacyPolicy/PrivacyPolicy";